

# EXCEPTION RESPONSE
RESPONSE_KEY_DETAIL = 'detail'
RESPONSE_KEY_MESSAGE = 'message'
RESPONSE_KEY_DATA = 'data'
RESPONSE_KEY_ERROR = 'error'
RESPONSE_KEY_STATUS_CODE = 'status_code'
RESPONSE_KEY_RESPONSE_DATA = "response_data"


# query params
PAGE_SIZE_QUERY_PARAM = 'page_size'
PAGINATION_DEFAULT_PAGE_SIZE = 10
PAGINATION_MAX_PAGE_SIZE = 999