# Generated by Django 4.1 on 2024-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_profile_app', '0002_remove_vendor_user_id_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
