# Generated by Django 4.1 on 2024-05-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor_profile_app', '0003_alter_vendor_average_response_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendorPerformanceHistory',
            fields=[
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('vendor_perf_id', models.AutoField(db_column='vendor_perf_id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendor_profile_app.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
